services:
  mysql_app:
    image: mysql:8.0.39
    container_name: mysql_school
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nokidding123456
      MYSQL_DATABASE: school_db
    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - school_net


volumes:
  mysql_data:

networks:
  school_net:
    driver: bridge
